### ISSUE TITLE
Icon spacing bug on Safari 13

### ISSUE THREAD

**Issue by healeycodes** [emgoto/emgoto.com#1]
On Safari 13, iOS 13.7, there appears to be a spacing bug with the icons under the title of a blog post.

![List of icons with large spaces between them](https://user-images.githubusercontent.com/34559231/94112466-69389f00-fe3d-11ea-8134-ed29f7876fe9.jpeg)

This is different from how it appears on Chrome mobile, so I thought I’d raise it in case it’s considered a bug 🐛

**Comment by emgoto** [comment]
Thanks so much for reporting this @healeycodes I really appreciate it! Just pushed a fix so it should be deployed within the next ~ 5 minutes.
